# Python review

Goals:
- recall basic Python vocabulary
- practice markdown

## Libraries and packages

**library**: a collection of code that we can use to perform specific tasks in our programs. 

**NumPy**:
- core library for numerical computing in Python
- many other libraries use NumPy arrays as building blocks
- computations on NumPy are optiomized for speed and memory usage

Let's import NumPy with **standard abbreviation**

*Trial update.*

In [1]:
import numpy as np

## Variables 

**variable**: a name we assign to a particular object in Python 

Example:

In [2]:
# Assign a small array to a variable a
a = np.array([[1,1,2],[3,5,8]])

In [3]:
# Run cell with the variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
# Use `print` function to print the value
print(a)

[[1 1 2]
 [3 5 8]]


## Objects

**object** (informally speaking) is a bundle of *properties* and *actions* about something specific. 

Example:

Object: data frame

Properties: number rows, names of the columns, date created

Actions: selecting a specific row, adding a new column 

A variable is the name we give a specific object, and the same object can be referenced by different variables. 

In practice, we can often use variable and object interchangeably. 